CREATE TABLE users(
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    password VARCHAR(255),
   
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


 ALTER TABLE users ADD COLUMN photoUrl VARCHAR(255);